'use strict';

    module.exports = {
        fbEmail : 'skill.bereg@gmail.com',
        fbPassword : 'federikofellini1920',
        loginButton : 'com.example.ivan.champy_v2:id/login_button',
        champyLogo : 'com.example.ivan.champy_v2:id/Champy_image',
        fbEmailField : 'com.facebook.katana:id/login_username',
        fbPasswordField : 'com.facebook.katana:id/login_password',
        fbLoginButton : 'com.facebook.katana:id/login_login',
        challengeBar : 'com.example.ivan.champy_v2:id/textView2',
        winsBar : 'com.example.ivan.champy_v2:id/textView3',
        totalBar : 'com.example.ivan.champy_v2:id/textView4',
        sliderCard : 'com.example.ivan.champy_v2:id/cardImage',
        plusButton : 'com.example.ivan.champy_v2:id/imageButton',
        sidemenuButton : 'android.widget.ImageButton',
        labelChallenges : 'Challenges',
        labelFriends : 'Friends',
        labelHistory : 'History',
        labelSettings : 'Settings',
        labelShare : 'Share',
        labelLogout : 'Logout',
        profileImage : 'com.example.ivan.champy_v2:id/profile_image',
        deleteFriendButton : 'com.example.ivan.champy_v2:id/imageButton2',
        pendingFriends : 'Pending',
        otherFriends : 'Other',
        labelGeneral : 'General:',
        labelName : 'Name',
        labelAvatar : 'Avatar',
        labelDeleteAccount : 'Delete Account',
        labelNotifications : 'Notifications:',
        labelLegal : 'Legal:',
        labelAbout: 'About',
        switchPushNotifications : 'com.example.ivan.champy_v2:id/switch1',
        switchChallengeRequests : 'com.example.ivan.champy_v2:id/switch2',
        switchAcceptedYourChallenge : 'com.example.ivan.champy_v2:id/switch3',
        switchChallengeEnd : 'com.example.ivan.champy_v2:id/switch4',
        labelPrivacyPolice : 'Privacy Police',
        labelTerms : 'Terms',
        labelContactUs : 'Contact Us',
        textPrivacyPolicy : 'com.example.ivan.champy_v2:id/textView1',
        screenSettings : 'com.example.ivan.champy_v2:id/back_settings'
    };